### ISSUE TITLE
generated code with a java style package header

### ISSUE THREAD

**Issue by BowenXiao1999** [rrevenantt/antlr4rust#39]
Hi, thanks for the huge effort first!

```
java -jar ~/antlr4-4.8-2-SNAPSHOT-complete.jar -Dlanguage=Rust -visitor -o ../gen SqlBase.g4
```

The generated visitor.rs or lexer.rs has both a java style package header. Are there something wrong with the options?
![image](https://user-images.githubusercontent.com/36908971/147066752-65546e60-9d3f-44d5-a0eb-c7e5d800e8a0.png)

**Comment by newca12** [comment]
Nothing wrong with your options. By the way I can't reproduce your problem. Where does com.risingwave come from ?

**Comment by BowenXiao1999** [comment]
I have a 
@header {
    package com.risingwave.sql.parser.antlr.v4;
}

in my g4 files (previous used for  java runtime).

Now I removed it and it do not appear. Thanks!
