### ISSUE TITLE
How to use listeners and visitors in 0.2?

### ISSUE THREAD

**Issue by DoctorBracewell** [rrevenantt/antlr4rust#44]
The code in `my_test.rs` indicates that a parser should have an `add_parse_listener` function that a listener can be paused to to run during parsing?

However, my parser in the code below has no such function:
```rust
let tf = CommonTokenFactory::default();
let input_stream = InputStream::new("test");
let lexer = OCRLexer::new_with_token_factory(input_stream, &tf);
let token_stream = CommonTokenStream::new(lexer);
let mut parser = OCRParser::new(token_stream);

// parser has no add_parse_listener
```

How can I add a listener to the parser, similar to these lines from `my_test.rs`?
```rust
let mut parser = CSVParser::new(token_source);
parser.add_parse_listener(Box::new(Listener {}));
println!("\nstart parsing parser_test_csv");
let result = parser.csvFile();
assert!(result.is_ok());
assert_eq!(
    result.unwrap().to_string_tree(&*parser),
    "(csvFile (hdr (row (field V123) , (field V2) \\n)) (row (field d1) , (field d2) \\n))"
);
```

**Comment by rrevenantt** [comment]
`add_parse_listener` is available via `DerefMut<Target=BaseParser<_>>` that is implemented on every parser, so i am not sure what exactly do you mean. Is there a particular error happening when you call it?

**Comment by DoctorBracewell** [comment]
Ah, for some reason it was the intellisense in my IDE not picking up that function, even though it still compiles and runs. Do you know why that might be the case?

**Comment by rrevenantt** [comment]
¯\_(ツ)_/¯ it works in intellij for me

**Comment by DoctorBracewell** [comment]
Weird, VSCode isn't too happy about it. Oh well!
