### ISSUE TITLE
Is It possible that generate AST for g4 file dynamically?

### ISSUE THREAD

**Issue by songtianyi** [rrevenantt/antlr4rust#48]
As I know, there is a plugin in Intellij IDEA that can preview the AST on the fly, is it possible in pure rust?

**Comment by yuriry** [comment]
@songtianyi If you are asking about ANTLR Preview tool window in IntelliJ: ANTLR Preview is independent of the target language.  It needs a g4 file and an input file (input can also be typed in the tool window directly).  I hope I understood your question correctly.

![image](https://user-images.githubusercontent.com/16765548/180607103-5db7e441-42ef-4642-8523-a7997b517d22.png)
