### ISSUE TITLE
ANTLR cannot generate Rust code as of version 4.13.1

### ISSUE THREAD

**Issue by woile** [rrevenantt/antlr4rust#84]
I get this error:

```
error(31):  ANTLR cannot generate Rust code as of version 4.13.1
```

I've followed the steps described:
```
git clone -b rust-target https://github.com/rrevenantt/antlr4
git submodule update --init --recursive --remote 
mvn -DskipTests install
```

Running the following fails:
```
antlr4 -Dlanguage=Rust Idl.g4
```

I was trying to build Avro's `g4`:
https://github.com/apache/avro/blob/main/share/idl_grammar/org/apache/avro/idl/Idl.g4

**Comment by newca12** [comment]
The error you get show that you are using the latest upstream fat jar with no support for the Rust target (similar to #82), you should use the generated fat jar located in `antlr4/tool/target/antlr4-4.8-2-SNAPSHOT-complete.jar`

**Comment by woile** [comment]
I've used that one, and I get the same error

**Comment by newca12** [comment]
There is no issue here, you just have to follow instructions carefully, Avro's g4 is building fine with Rust target.

**Comment by woile** [comment]
Any idea what may I be missing? I'm gonna give it another try. Thanks

**Comment by woile** [comment]
I've removed the folder, followed the steps again, and finally run:

```sh
 java -jar ./antlr4/tool/target/antlr4-4.8-2-SNAPSHOT-complete.jar -Dlanguage=Rust Idl.g4
```

And I still get `error(31):  ANTLR cannot generate Rust code as of version 4.8`

```sh
$ java -version
openjdk version "11.0.18" 2023-01-17 LTS
```

```sh
$ mvn -version
Apache Maven 3.9.4
```

thoughts?

**Comment by woile** [comment]
Well I downloaded the released version of this jar and it works 🤷🏻

**Comment by pedro-gilmora** [comment]
> Well I downloaded the released version of this jar and it works 🤷🏻

Hi, can you provide a boilerplate template?
